services:
  db:
    image: postgres:15
    env_file:
      - ./.env
    container_name: recipe-db
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5555:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
    postgres_db:
        driver: local
